// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace $safeprojectname$
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string $safeprojectname$String = "$guid3$";
        public static Guid $safeprojectname$ = new Guid($safeprojectname$String);

        public const string IconsString = "$guid4$";
        public static Guid Icons = new Guid(IconsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MainMenu = 0x1010;
        public const int MyMenuGroup = 0x1020;
        public const int SubMenuGroup = 0x1030;
        public const int HRMenuGroup = 0x1040;
        public const int Wiki = 0x0100;
        public const int BuildServer = 0x0200;
        public const int HrPortal = 0x0300;
        public const int Logo = 0x0001;
    }
}