// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace $safeprojectname$
{
    internal sealed partial class Vsix
    {
        public const string Id = "$safeprojectname$.$guid2$";
        public const string Name = "$safeprojectname$";
        public const string Description = @"$description$";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "$registeredorganization$";
        public const string Tags = "";
    }
}
