// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixItemTemplates.ItemTemplates.Package
{
    internal sealed partial class Vsix
    {
        public const string Id = "$guid1$";
        public const string Name = "$packageName$";
        public const string Description = @"$packageName$ Visual Studio Package";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "$registeredorganization$";
        public const string Tags = "";
    }
}
