// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixItemTemplates
{
    internal sealed partial class Vsix
    {
        public const string Id = "88049e1e-62f2-4ea2-851f-9ddb2de37f41";
        public const string Name = "Extensibility Template Pack";
        public const string Description = @"A template pack for Visual Studio extension authors full of useful project- and item templates.";
        public const string Language = "en-US";
        public const string Version = "2.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vsix, extension, template";
    }
}
